/** GitHub-shaped repo fixtures for tests (only the fields our schema reads). */
export const githubReposFixture = [
  {
    id: 1,
    name: 'winfolio',
    description: 'A Windows 95 desktop portfolio built with React.',
    language: 'TypeScript',
    topics: ['react', 'vite', 'tailwind'],
    html_url: 'https://github.com/rjamador/winfolio',
    homepage: 'https://winfolio.example.com',
    stargazers_count: 42,
    forks_count: 5,
    fork: false,
    archived: false,
    updated_at: '2026-05-01T12:00:00Z',
  },
  {
    id: 2,
    name: 'pixel-paint',
    description: 'A tiny bitmap editor.',
    language: 'JavaScript',
    topics: ['canvas'],
    html_url: 'https://github.com/rjamador/pixel-paint',
    homepage: '',
    stargazers_count: 10,
    forks_count: 1,
    fork: false,
    archived: false,
    updated_at: '2025-11-10T08:30:00Z',
  },
  {
    id: 3,
    name: 'task-tray',
    description: null,
    language: null,
    topics: [],
    html_url: 'https://github.com/rjamador/task-tray',
    homepage: null,
    stargazers_count: 0,
    forks_count: 0,
    fork: false,
    archived: false,
    updated_at: '2024-02-20T16:45:00Z',
  },
  {
    id: 4,
    name: 'forked-lib',
    description: 'A fork that should be filtered out.',
    language: 'Go',
    topics: [],
    html_url: 'https://github.com/rjamador/forked-lib',
    homepage: null,
    stargazers_count: 99,
    forks_count: 0,
    fork: true,
    archived: false,
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 5,
    name: 'old-archived',
    description: 'An archived repo that should be filtered out.',
    language: 'Ruby',
    topics: [],
    html_url: 'https://github.com/rjamador/old-archived',
    homepage: null,
    stargazers_count: 7,
    forks_count: 0,
    fork: false,
    archived: true,
    updated_at: '2023-01-01T00:00:00Z',
  },
]
