/** GitHub-shaped repo fixtures for tests (only the fields our schema reads). */
export const githubReposFixture = [
  {
    id: 1,
    name: 'GymCheck',
    description: 'A gym attendance tracker.',
    language: 'PHP',
    topics: ['php', 'mysql'],
    html_url: 'https://github.com/rjamador/GymCheck',
    homepage: 'https://gymcheck.example.com',
    stargazers_count: 7,
    forks_count: 2,
    fork: false,
    archived: false,
    updated_at: '2026-05-01T12:00:00Z',
  },
  {
    id: 2,
    name: 'portfolio',
    description: 'A Windows 95 desktop portfolio built with React.',
    language: 'TypeScript',
    topics: ['react', 'vite'],
    html_url: 'https://github.com/rjamador/portfolio',
    homepage: '',
    stargazers_count: 4,
    forks_count: 0,
    fork: false,
    archived: false,
    updated_at: '2025-11-10T08:30:00Z',
  },
  {
    id: 3,
    name: 'Coinflow',
    description: 'A finance dashboard.',
    language: 'TypeScript',
    topics: [],
    html_url: 'https://github.com/rjamador/Coinflow',
    homepage: null,
    stargazers_count: 1,
    forks_count: 0,
    fork: false,
    archived: false,
    updated_at: '2024-02-20T16:45:00Z',
  },
  {
    id: 4,
    name: 'random-side-project',
    description: 'Not in the allowlist; should be filtered out.',
    language: 'Go',
    topics: [],
    html_url: 'https://github.com/rjamador/random-side-project',
    homepage: null,
    stargazers_count: 99,
    forks_count: 0,
    fork: false,
    archived: false,
    updated_at: '2026-06-01T00:00:00Z',
  },
  {
    id: 5,
    name: 'forked-lib',
    description: 'A fork that should be filtered out.',
    language: 'Go',
    topics: [],
    html_url: 'https://github.com/rjamador/forked-lib',
    homepage: null,
    stargazers_count: 50,
    forks_count: 0,
    fork: true,
    archived: false,
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 6,
    name: 'Perfumeria',
    description: 'An archived repo that should be filtered out.',
    language: 'Visual Basic .NET',
    topics: [],
    html_url: 'https://github.com/rjamador/Perfumeria',
    homepage: null,
    stargazers_count: 30,
    forks_count: 0,
    fork: false,
    archived: true,
    updated_at: '2023-01-01T00:00:00Z',
  },
]
